// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH7HotwMkAJfJLhpfQaIw7F2VH0A54otw',
    appId: '1:766825819406:web:581f6aa2fdfdbff815fb5f',
    messagingSenderId: '766825819406',
    projectId: 'imdb-clone-1ee89',
    authDomain: 'imdb-clone-1ee89.firebaseapp.com',
    storageBucket: 'imdb-clone-1ee89.appspot.com',
    measurementId: 'G-FYLJGCDHVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_8XPRZdeWga0qkmlSLCPSs49r5UdcXo8',
    appId: '1:766825819406:android:ca8a06f29f32e70e15fb5f',
    messagingSenderId: '766825819406',
    projectId: 'imdb-clone-1ee89',
    storageBucket: 'imdb-clone-1ee89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqvKp7E1gluCnhG2_94aDPgUN0IZ7vNzs',
    appId: '1:766825819406:ios:823a6e1407e2df4215fb5f',
    messagingSenderId: '766825819406',
    projectId: 'imdb-clone-1ee89',
    storageBucket: 'imdb-clone-1ee89.appspot.com',
    iosClientId: '766825819406-4ssal3mi04la06363r9oraiquujpm4je.apps.googleusercontent.com',
    iosBundleId: 'com.example.imdbClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqvKp7E1gluCnhG2_94aDPgUN0IZ7vNzs',
    appId: '1:766825819406:ios:823a6e1407e2df4215fb5f',
    messagingSenderId: '766825819406',
    projectId: 'imdb-clone-1ee89',
    storageBucket: 'imdb-clone-1ee89.appspot.com',
    iosClientId: '766825819406-4ssal3mi04la06363r9oraiquujpm4je.apps.googleusercontent.com',
    iosBundleId: 'com.example.imdbClone',
  );
}
